name: aust4
description: "The school app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cupertino_icons: ^1.0.8

  google_maps_flutter: ^2.1.1
  location: ^4.4.0
  flutter_dotenv: ^5.2.1
  path_provider: ^2.0.13
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.3.7
  provider: ^6.1.2
  http: ^1.2.2 # For HTTP requests to Cloudinary


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/aust_logo.png # Correct placement of assets section

dependency_overrides:
  async: ^2.12.0
  boolean_selector: ^2.1.2
  characters: ^1.4.0
  clock: ^1.1.2
  collection: ^1.19.1
  fake_async: ^1.3.2
  leak_tracker: ^10.0.8
  leak_tracker_flutter_testing: ^3.0.9
  matcher: ^0.12.17
  material_color_utilities: ^0.12.0
  meta: ^1.16.0
  path: ^1.9.1
  source_span: ^1.10.1
  stack_trace: ^1.12.1
  stream_channel: ^2.1.3
  string_scanner: ^1.4.1
  term_glyph: ^1.2.2
  test_api: ^0.7.4
  js: ^0.7.1
  location: ^7.0.1
  location_platform_interface: ^5.0.0
  location_web: ^5.0.4
  vm_service: ^15.0.0